baseURL = 'https://danailov.it/'
languageCode = 'en'
DefaultContentLanguage = 'it'
title = 'Prova sito'
author = 'Natanail Danailov'
theme = 'paper'
ignoreErrors = ["error-remote-getjson"]

# --------------------------------

[params]
    color = 'linen'           # linen, wheat, gray, light

    github = 'natanail'
    instagram = 'natanaild'
    linkedin = 'ndanailov'
    threads = '@natanaild'

    avatar = 'danailovnatanail@gmail.com'
    name = 'Natanail Danailov'

[menu]

    [[menu.main]]
        identifier = "chisono"
        name = "Chi sono"
        url = "/chi-sono/"
        weight = 10
    [[menu.main]]
        identifier = "progetti"
        name = "Progetti"
        url = "/progetti/"
        weight = 20
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 30

[taxonomies]
category = "categorie"
tag = "tag"
series = "serie"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

# misc

monoDarkIcon = true

ignoreErrors = ["error-remote-getjson"]

math = true                               # enable KaTeX math typesetting globally

localKatex = true                         # use local KaTeX js/css instead of CDN

favicon = "favicon.ico"                   # customize the default favicon

appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon